import * as All from "../assets/index";

export const HUSTLETABLES = [
  {
    id: 0,
    name: "Rockerboy",
    img: require("./images/rockerboy.png"),
    avatar: "/images/rockerboyAvatar.png",
    tableArr: [
      {
        description: `Played a small local gig.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `No gigs or jobs to be had this week.`,
        level1: 0,
        level2: 100,
        level3: 300,
      },
      {
        description: `Played a big gig for a rich Corporate or Local Personality.`,
        level1: 300,
        level2: 500,
        level3: 800,
      },
      {
        description: `Got some royalties in for your most recent Data Pool download.`,
        level1: 300,
        level2: 500,
        level3: 800,
      },
      {
        description: `Opening act for a Big-Name group`,
        level1: 300,
        level2: 500,
        level3: 800,
      },
      {
        description: `Personal appearance netted you a large fee.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
    ],
  },
  {
    id: 1,
    name: "Solo",
    img: "/images/solo.png",
    avatar: "/images/soloAvatar.png",
    tableArr: [
      {
        description: `Bodyguard work, low-end client.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Bodyguard work, high-end client.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Difficult hit or extraction.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Hired out as muscle to a Fixer, Corp, or Gang.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Attracted undue attention, had to lay low.`,
        level1: 0,
        level2: 100,
        level3: 300,
      },
      {
        description: `Basic enforcer or hitman work for a local Corp.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
    ],
  },
  {
    id: 2,
    name: "Netrunner",
    img: "/images/netrunner.png",
    avatar: "/images/netrunnerAvatar.png",
    tableArr: [
      {
        description: `Cracked a small system and sold the data.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Cracked a major Corporate system and sold the data.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `You got sidetracked and didn't hack anything this week`,
        level1: 0,
        level2: 100,
        level3: 300,
      },
      {
        description: `Found a valuable cache in an abandoned system and sold it.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Brought down a minor system with ransomware and got paid off to uninstall it.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Sabotaged or otherwise disabled a major system for a faceless client.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
    ],
  },
  {
    id: 3,
    name: "Tech",
    img: "/images/tech.png",
    avatar: "/images/techAvatar.png",
    tableArr: [
      {
        description: `No jobs this week.`,
        level1: 0,
        level2: 100,
        level3: 300,
      },
      {
        description: `Rebuilt some tech you scavenged in the Combat Zone.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Helped a client break into some place or installed security systems for a client.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Did some modifications or repairs to some cybertech.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Did some modifications or repairs to some weapons`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Sabotaged or otherwise disabled something for a client.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
    ],
  },
  {
    id: 4,
    name: "Medtech",
    img: "/images/medtech.png",
    avatar: "/images/medtechAvatar.png",
    tableArr: [
      {
        description: `Patched up someone after a firefight.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Sold cyberware from a 'failed' medical case.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Helped Trauma Team on some backup work when they were overloaded`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Did some minor "free clinc" work for locals. You can't eat goodwill, though.`,
        level1: 0,
        level2: 100,
        level3: 300,
      },
      {
        description: `Did a major medical procedure for a very well-heeled client.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Designed and delivered medicines or street drugs to a client.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
    ],
  },
  {
    id: 5,
    name: "Media",
    img: "/images/media.png",
    avatar: "/images/mediaAvatar.png",
    tableArr: [
      {
        description: `Wrote an expose that covered a major topic, made a big sale.`,
        level1: 300,
        level2: 500,
        level3: 800,
      },
      {
        description: `Wrote a popular "puff piece" that got you some notice and some cash.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Did some boring ad writing to pay the bills.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Exposed a big story that got you a few enemies and some cash.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `No good stories or leads this week.`,
        level1: 0,
        level2: 100,
        level3: 300,
      },
      {
        description: `Wrote an expose that blew the lid off a major topic.`,
        level1: 300,
        level2: 500,
        level3: 800,
      },
    ],
  },
  {
    id: 6,
    name: "Lawman",
    img: "/images/lawman.png",
    avatar: "/images/lawmanAvatar.png",
    tableArr: [
      {
        description: `Made a few minor busts, business as usual.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Got a reward from a grateful citizen. Or was it a bribe?`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Bust went bad, and it came out of your salary.`,
        level1: 0,
        level2: 100,
        level3: 300,
      },
      {
        description: `Nothing much happened this week. Collected a paycheck and that was it`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Pulled off a major drug or smuggling bust and gained a bonus from the boss`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Took down a big gang and got some of a "civil seizure" bonus.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
    ],
  },
  {
    id: 7,
    name: "Exec",
    img: "/images/exec.png",
    avatar: "/images/execAvatar.png",
    tableArr: [
      {
        description: `Landed a moderate success on a project, earned a reward bonus.`,
        level1: 300,
        level2: 500,
        level3: 800,
      },
      {
        description: `Nothing much happened, and Coporate was unimpressed. Lost a bonus.`,
        level1: 0,
        level2: 100,
        level3: 300,
      },
      {
        description: `Collected a paycheck and that was it.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Got some dirt on a rival and used it to scare a bonus.`,
        level1: 300,
        level2: 500,
        level3: 800,
      },
      {
        description: `Pulled off a major project success and gained a bonus from the Head Office.`,
        level1: 300,
        level2: 500,
        level3: 800,
      },
      {
        description: `Took out a legitimate target that was threatening a job and took their funding.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
    ],
  },
  {
    id: 8,
    name: "Fixer",
    img: "/images/fixer.png",
    avatar: "/images/fixerAvatar.png",
    tableArr: [
      {
        description: `Got a Media some information for a good bribe.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Got Rocker a good Gig for your 12% fee.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Helped a client locate a desirable item they needed and got a cut.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Deal went south; you're keeping your head down 'till it blows over.`,
        level1: 0,
        level2: 100,
        level3: 300,
      },
      {
        description: `Got a Solo or Netrunner a profitable "job" and took your agency fee.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Brought in a rare, illegal, or very hard to get item for a client.`,
        level1: 300,
        level2: 500,
        level3: 800,
      },
    ],
  },
  {
    id: 9,
    name: "Nomad",
    img: "/images/nomad.png",
    avatar: "/images/nomadAvatar.png",
    tableArr: [
      {
        description: `Made a legit shipment.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Protected a shipment.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Smuggled some small contraband.`,
        level1: 10,
        level2: 200,
        level3: 500,
      },
      {
        description: `Smuggled a huge shipment.`,
        level1: 200,
        level2: 300,
        level3: 600,
      },
      {
        description: `Delivered a client safely to a destination.`,
        level1: 100,
        level2: 200,
        level3: 500,
      },
      {
        description: `Couldn't find work this week, legit or otherwise.`,
        level1: 0,
        level2: 100,
        level3: 300,
      },
    ],
  },
];
